### ISSUE TITLE
Autenticazione

### ISSUE THREAD

**Issue by marll** [satispay/gbusiness-api-php-sdk#1]
Salve,
utilizzando la seguente chiamata:
$authentication = \SatispayGBusiness\Api::authenticateWithToken("PVS5T3");
la libreria mi ritorna il seguente errore:
PHP Warning:  openssl_pkey_export(): cannot get key from parameter 1 in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\xmsoftit\\ex\\vendor\\satispay\\gbusiness-api-php-sdk\\lib\\Api.php on line 29, referer: http://xmsoft.ikwb.com/xmsoftit/ex/?page=satispay
PHP Warning:  openssl_pkey_get_details() expects parameter 1 to be resource, boolean given in C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\xmsoftit\\ex\\vendor\\satispay\\gbusiness-api-php-sdk\\lib\\Api.php on line 31, referer: http://xmsoft.ikwb.com/xmsoftit/ex/?page=satispay
PHP Fatal error:  Uncaught Exception: Bad request or invalid json, request id: 9OFojGLO in 
C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\xmsoftit\\ex\\vendor\\satispay\\gbusiness-api-php-sdk\\lib\\Request.php:188\nStack trace:\n#0 
C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\xmsoftit\\ex\\vendor\\satispay\\gbusiness-api-php-sdk\\lib\\Request.php(41): SatispayGBusiness\\Request::request(Array)\n#1 
C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\xmsoftit\\ex\\vendor\\satispay\\gbusiness-api-php-sdk\\lib\\Api.php(37): SatispayGBusiness\\Request::post('/g_business/v1/...', Array)\n#2 
C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\xmsoftit\\ex\\content\\satispay\\UtilsSatispay\\SatispayRSAKey.php(15): SatispayGBusiness\\Api::authenticateWithToken('PVS5T3')\n#3 
C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\xmsoftit\\ex\\content\\satispay\\form.php(10): UtilsSatispay\\SatispayRSAKey->CreateKey()\n#4 {main}\n  thrown in
 C:\\Program Files (x86)\\EasyPHP-Devserver-17\\eds-www\\xmsoftit\\ex\\vendor\\satispay\\gbusiness-api-php-sdk\\lib\\Request.php on line 188, 

Grazie

**Comment by adnsio** [comment]
Ciao,

versione di PHP?

**Comment by marll** [comment]
7.1.3

**Comment by adnsio** [comment]
La libreria non è stata testata su Windows, in ogni caso è un Warning, se non hai errori puoi anche ignorarlo.

**Comment by marll** [comment]
Questo è l'errore:
PHP Fatal error: Uncaught Exception: Bad request or invalid json, request id: 9OFojGLO in
C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\xmsoftit\ex\vendor\satispay\gbusiness-api-php-sdk\lib\Request.php:188\nStack trace:\n#0

**Comment by adnsio** [comment]
C'è qualcosa di errato nella richiesta. Prova ad utilizzare gli esempi contenuti in questo repository.

**Comment by marll** [comment]
Eseguo le stesse chiamate dell'esempio.
Di seguito le chiamate che faccio:
\SatispayGBusiness\Api::setSandbox(true);
$authentication = \SatispayGBusiness\Api::authenticateWithToken("PVS5T3");
Dove il valore PVS5T3 mi è stato fornito insieme all'account.

**Comment by marll** [comment]
Ho provato ad utilizzare anche il token WG5MUC che contenuto negli esempi, ma il risultato è sempre lo stesso

**Comment by marll** [comment]
Era un problema di configurazione di openssl su windows

**Comment by marll** [comment]
Ora sto avendo un problema nella chiamata \SatispayGBusiness\Consumer::get per rintracciare l'id del consumer dal numero di telefono.
Il problema sembra verificarsi nel file request.php, la seguente chiamata 
$curlResult = self::curl(array(
      "url" => Api::getAuthservicesUrl().$options["path"],
      "method" => $method,
      "body" => $body,
      "headers" => $headers
    ));
dove url=https://staging.authservices.satispay.com/g_business/v1/consumers/38900000000
method=GET
body=
header=Array\n(\n    [0] => Accept: application/json\n    [1] => User-Agent: SatispayGBusinessApiPhpSdk/1.0.0\n    [2] => Date: Fri, 01 Feb 2019 20:04:28 +0100\n    [3] => Authorization: Signature keyId="6ri84qn7hg0qujtmrh7u74bkqid8nvis47fvk51i0d0ugktcl8qoikl5ppeai5nej9acbg2svr5dj3fbe5b75850t92sn8m84nthm8genuposgrlbgi34h7qom0sadg6c37c035u1k8tnt7f7r5b10o607lsfd1ummaqjpgi6jfkc0jhl55u4jhq2isps48pbpp2ekku", algorithm="rsa-sha256", headers="(request-target) host date", signature="e44+jsyYZXrkGeIroLsbpxvi+FMeNoD91scgvFT2lBjA/ObktmyA8diyEllKXqwQcX6nativC0MT3IrodktdsoFFfXWz+sw9X0Ax3yHc08xdzrO31CD6f3D/6a5As5g6x65Zmp5CsU9uwMSTbsAr9jB8M9EWe4r4rpokbgh9057eeiiCvDqvI6aMgKTQT4EX8hoZSMVC/jWUMsjHcUAFeEzoKrOdTlhjiWY/e97UFlVVI4GIJ+o16SZl5jBYzJLW3taLLmpCUANR0HZEeiIHpAtwgi5z+j7BAtsN6dr8FwU9PZVAZd87uHS8I2J0wKolKKzbQyuNbkIm5BQEXjWQmQ=="\n)\n
torna il seguente errore:
Array\n(\n    [body] => {"code":41,"message":"Resource not found","wlt":"GspkkUQP"}\n    [status] => 404\n    [errorCode] => 0\n    [errorMessage] => \n)\n, 
Grazie

**Comment by adnsio** [comment]
Ciao, non è un errore. Semplicemente il numero non è registrato in Satispay.

**Comment by marll** [comment]
Ciao,
il numero che mando è il numero associato al mio account.
Nel log che ti ho mandato l'ho modificato per motivi di privacy

**Comment by nutella** [comment]
> Era un problema di configurazione di openssl su windows

Visto che ho lo stesso problema ma su OsX e su linux, puoi dirmi come lo hai risolto?

Grazie...

**Comment by m-bonanno** [comment]
> Era un problema di configurazione di openssl su windows

Potresti spiegare come hai fatto a configurare correttamente openssl su Windows? Sto avendo lo stesso errore anche io.

**Comment by nutella** [comment]
> > Era un problema di configurazione di openssl su windows 
> Potresti spiegare come hai fatto a configurare correttamente openssl su Windows? Sto avendo lo stesso errore anche io.

Fai attenzione perche' io avevo lo stesso errore ma solo perche' usavo i codici dell'ambiente di produzione facendo le chiamate all'ambiente di test. Se vuoi fare dei test devi usare l'app e l'ambiente di test, puoi richiedere l'attivazione scrivendo a business@satispay.com
