### ISSUE TITLE
Authentication forbidden [Help request]

### ISSUE THREAD

**Issue by andrecolza** [satispay/gbusiness-api-php-sdk#10]
I'm trying to authenticate in my sandbox account to retrieve my auth keys, I'm doing the follow:
```php
\SatispayGBusiness\Api::setSandbox(true);
$authentication = \SatispayGBusiness\Api::authenticateWithToken($mySandboxToken);
```
but I get exception "Forbidden, request id: XXXXXXXX" with code 45.

![immagine](https://user-images.githubusercontent.com/58806953/136411741-49ffbb60-3000-469a-ad19-aa2434028570.png)

What I'm wrong?

Thanks,
Andrea

**Comment by stvnmsh** [comment]
Hi @andrecolza, please write an email at tech@satispay.com for this kind of requests
