### ISSUE TITLE
Unauthorized, request id

### ISSUE THREAD

**Issue by DanezBs** [satispay/gbusiness-api-php-sdk#2]
Ho un problema di autenticazione con il seguente codice:
\SatispayGBusiness\Api::setSandbox(true);
\SatispayGBusiness\Api::setSecurityBearer($authData->security_bearer);
$result = \SatispayGBusiness\Api::testAuthentication();

dove $authData->security_bearer è il valore preso dal mio account Business.
l'errore che mi torna è "Unauthorized, request id: q4UWU20r"
il tutto gira su un linux con php 7.x

**Comment by adnsio** [comment]
Ciao puoi scrivere una richiesta supporto alla mail: business@satispay.com

Grazie
