### ISSUE TITLE
Idempotency key

### ISSUE THREAD

**Issue by tobiascapin** [satispay/gbusiness-api-php-sdk#5]
Come si può impostare una Idempotency-Key nell'header della chiamata?

**Comment by stiven-satispay** [comment]
L'Idempotency-Key non è un campo required per effettuare le chiamate alle nostre API e quindi non viene impostata dalla libreria. Trovi maggiori informazioni sulla nostra [documentazione](https://developers.satispay.com/reference#idempotency).
