### ISSUE TITLE
Is it possibile to have a PSR-3 Logger?

### ISSUE THREAD

**Issue by tobiascapin** [satispay/gbusiness-api-php-sdk#9]
Is there any way to log somehow the satispay errors and API communications using a PSR-3 logger?
If not possible, are there any call interceptor where I can add the logger?
Thanks

**Comment by tobiascapin** [comment]
How can I debug a transaction if I cannot log the REST exchange?

**Comment by stvnmsh** [comment]
Hi @tobiascapin, you can enable the `CURLOPT_VERBOSE` of your php server for debugging.
